### PR TITLE
Update the import paths for Caddy

### PR DESCRIPTION
**Pull request by whalehub**
This pull request makes caddy-filemanager compatible with Caddy v1.0.1+ (see epicagency/caddy-expires#6 for reference) by updating the import paths for Caddy.

### CODE REVIEW

**Comment by whalehub** [comment]
@bronzehedwick Could you please have a look at this PR?

**Comment by bronzehedwick** [comment]
Hi @whalehub, this seems fine, but something to note:

I do not know how I became the owner of this repository. I was a user of caddy-filemanager some years ago, and contributed to the issue queue, but have never contributed code. I never asked to be or was made aware that I would be the maintainer of this project - I don't know go.

The first indication that I was the owner of this project was when you pinged me.

It seems like @hacdias is the actual author of the project, who can maybe shed some light on how the situation arose?

Thanks all.

**Comment by hacdias** [comment]
@bronzehedwick I believe you might've forked a repository I ended up deleting so you were made the owner of your own fork. As far as I can see, this repository isn't updated since 2016.

In other news, @whalehub File Browser **is not** a Caddy plugin since May. Please [see this issue](https://github.com/filebrowser/filebrowser/issues/723) for more information.

**Comment by whalehub** [comment]
@hacdias Thanks for the info.

**Comment by bronzehedwick** [comment]
Thanks for the insight @hacdias, much appreciated. That all tracks.

**Pull request closed without merging**
